//QUESTIONS STATUS
//NEW, WAITING, CLOSED
export const QUESTION_STATUS_NEW = 'QUESTION_STATUS_NEW'
export const QUESTION_STATUS_WAITING = 'QUESTION_STATUS_WAITING'
export const QUESTION_STATUS_CLOSED = 'QUESTION_STATUS_CLOSED'
export const QUESTION_STATUS_CANCELLED = 'QUESTION_STATUS_CANCELLED'


//QUESTIONS CATEGORIES
export const QUESTION_TYPE_EVENT = 'EVENT'
export const QUESTION_TYPE_FOOD = 'FOOD'
export const QUESTION_TYPE_SURPRISE = 'SURPRISE'
export const QUESTION_TYPE_FUN = 'FUN'
export const QUESTION_TYPE_HOTEL = 'HOTEL'


// ANSWERS status
export const ANSWER_STATUS_WAITING = 'ANSWER_STATUS_WAITING'
export const ANSWER_STATUS_REPLIED = 'ANSWER_STATUS_REPLIED'
