
// AUTH
export const INIT_AUTH ='INIT_AUTH'
export const SET_PROFILE = 'SET_PROFILE'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const USER_LOGOUT = 'USER_LOGOUT'


export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS'
export const FACEBOOK_LOGIN_FAIL = 'FACEBOOK_LOGIN_FAIL'
export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS'
export const GOOGLE_LOGIN_FAIL = 'GOOGLE_LOGIN_FAIL'


//QUESTIONS
export const INIT_QUESTIONS = 'INIT_ALL_QUESTIONS'
export const ADD_QUESTION = 'ADD_QUESTION'
export const DELETE_QUESTION = 'DELETE_QUESTION'
export const UPDATE_QUESTION = 'UPDATE_QUESTION'


//chat
export const INIT_CHAT = 'INIT_CHAT'
export const CLEAR_CHAT = 'CLEAR_CHAT'
export const ADD_MESSAGE = 'ADD_MESSAGE'

//location
export const CHANGE_LOCATION = 'CHANGE_LOCATION'
