//QUESTIONS STATUS
//NEW, WAITING, CLOSED
export const QUESTION_STATUS_NEW = 'QUESTION_STATUS_NEW'
export const QUESTION_STATUS_WAITING = 'QUESTION_STATUS_WAITING'
export const QUESTION_STATUS_CLOSED = 'QUESTION_STATUS_CLOSED'
export const QUESTION_STATUS_CANCELLED = 'QUESTION_STATUS_CANCELLED'


//QUESTIONS CATEGORIES
export const QUESTION_TYPE_EVENT = 'EVENT'
export const QUESTION_TYPE_FOOD = 'FOOD'
export const QUESTION_TYPE_SURPRISE = 'SURPRISE'
export const QUESTION_TYPE_FUN = 'FUN'
export const QUESTION_TYPE_HOTEL = 'HOTEL'


// ANSWERS status
export const ANSWER_STATUS_WAITING = 'ANSWER_STATUS_WAITING'
export const ANSWER_STATUS_REPLIED = 'ANSWER_STATUS_REPLIED'


//USER STATUS
export const USER_NEW_USER ='USER_NEW_USER'
export const USER_REGION_SELECTED   ='USER_REGION_SELECTED'
export const USER_REGISTERED_COMPLETE ='USER_REGISTERED_COMPLETE'

//CHATROOM STATUS
export const CHATROOM_STATUS_OPEN     ='OPEN'
export const CHATROOM_STATUS_CLOSED   ='CLOSE'

